version: '3.1'

services:
  dbcontracts:
    build: ./db
    restart: always
    environment:
      POSTGRES_DB: contracts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata    
    ports:
      - 2348:5432   
    volumes:
      - ./databases:/var/lib/postgresql/data/pgdata    
    networks: 
      - backend
  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080
  contracts:
    build: ./contracts
    ports:
      - 8007:8007
    links:
     - dbcontracts
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"    
